from asyncio import exceptions
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
import mouse
from selenium.webdriver.common.action_chains import ActionChains
import xlsxwriter
import time

STARPAGE = 7
ENDPAGE = 12 #max 174



workbook = xlsxwriter.Workbook("mapping-p1.xlsx")
worksheet = workbook.add_worksheet()
worksheet.write('A1', 'Mã khách hàng')
worksheet.write('B1', 'Tên khách hàng')
worksheet.write('C1', 'Địa chỉ')
worksheet.write('D1', 'Tên thường gọi')
worksheet.write('E1', 'Số hộ')
worksheet.write('F1', 'Số khẩu')
worksheet.write('G1', 'Email')
worksheet.write('H1', 'Ngày cấp CMND')
worksheet.write('I1', 'Nơi cấp CMND')
worksheet.write('J1', 'Mã số thuế')
worksheet.write('K1', 'Người đại điện')
worksheet.write('L1', 'Đối tượng')
worksheet.write('M1', 'Ghi chú')
worksheet.write('N1', 'Số hợp đồng')
worksheet.write('O1', 'ĐT giá')
worksheet.write('P1', 'Mục đích SD')
worksheet.write('Q1', 'Hình thức thanh toán')
worksheet.write('R1', 'Mã vạch')
worksheet.write('S1', 'Ngày ký')
worksheet.write('T1', 'Ngày lắp đặt')
worksheet.write('U1', 'Người lắp đặt')
worksheet.write('V1', 'ngàyNT')
worksheet.write('W1', 'Tiền lắp đặt')
worksheet.write('X1', 'Người nộp')
worksheet.write('Y1', 'Tiền đặt cọc')
worksheet.write('Z1', 'Giảm trừ theo')
worksheet.write('AA1', 'Số tiền giảm trừ')
worksheet.write('AB1', 'Ngày đặt cọc')
worksheet.write('AC1', 'Chứng từ đặt cọc')
worksheet.write('AD1', 'Cam kết sử dụng nước')
worksheet.write('AE1', 'Khối lượng cam kết')
worksheet.write('AF1', 'Ghi chú hợp đồng')
worksheet.write('AG1', 'Tĩnh')
worksheet.write('AH1', 'Huyện')
worksheet.write('AI1', 'Xã')
worksheet.write('AJ1', 'Vùng')
worksheet.write('AK1', 'Khu vực')
worksheet.write('AL1', 'Nhân viên')
worksheet.write('AM1', 'Tuyến đọc')
worksheet.write('AN1', 'Phạm vi')
worksheet.write('AO1', 'Mã đồng hồ')
worksheet.write('AP1', 'Đồng hồ block')
worksheet.write('AQ1', 'Là đồng hồ phụ')
worksheet.write('AR1', 'Số thứ tự')
worksheet.write('AS1', 'Seri')
worksheet.write('AT1', 'Chỉ số đầu')
worksheet.write('AU1', 'Chỉ số cuối')
worksheet.write('AV1', 'Seri chỉ')
worksheet.write('AW1', 'Ngày lắp đặt đồng hồ')
worksheet.write('AX1', 'Ngày sử dụng')
worksheet.write('AY1', 'Địa chỉ')
worksheet.write('AZ1', 'Trạng thái')
worksheet.write('BA1', 'Lý do hủy')
worksheet.write('BB1','Ngày BĐ ngừng')
worksheet.write('BC1','Ngày kết thúc')
worksheet.write('BD1', 'Nước SX')
worksheet.write('BE1', 'Hãng SX')
worksheet.write('BF1', 'Kiểu đồng hồ')
worksheet.write('BG1', 'Đường kính')
worksheet.write('BH1', 'Hộp bảo vệ')
worksheet.write('BI1', 'Vị trí lắp đặt')
worksheet.write('BJ1', 'Ngày kiểm định')
worksheet.write('BK1', 'Ngày hết KĐ')
worksheet.write('BL1', 'Lý do kiểm định')
worksheet.write('BM1', 'Van một chiều')
worksheet.write('BN1', 'Tem')
worksheet.write('BO1', 'Số phiếu thay')
worksheet.write('BP1', 'Hình thức xử lý')
worksheet.write('BQ1', 'Lý do thay')
worksheet.write('BR1', 'Mã đồng hỗ thay')
worksheet.write('BS1', 'Người thay')
worksheet.write('BT1', 'Kinh độ')
worksheet.write('BU1', 'Vĩ độ')
worksheet.write('BV1', 'Lọa KM')
worksheet.write('BW1', 'Khuyến mãi')
worksheet.write('BX1', 'Trạng thái ĐH lắp')
worksheet.write('BY1', 'Ống dẫn')
worksheet.write('BZ1', 'Đai khởi thủy')

driver = webdriver.Chrome()
driver.get("https://app.citywork.vn/gcrm.aspx")
driver.maximize_window()
ID = driver.find_elements(By.CSS_SELECTOR,'div.col_full:nth-child(1)>input')
ID[0].send_keys("AT_Test")

PASS = driver.find_elements(By.CSS_SELECTOR,'div.col_full:nth-child(2)>input')
PASS[0].send_keys("1234567890Aa")
BTN = driver.find_elements(By.ID,'ctl00_mainContent_login1_LoginCtrl_Login')
BTN[0].click()
time.sleep(5)






driver.find_element(By.ID,'ext-gen1202').click()
time.sleep(2)
def save():
    maTinh  = table.find_element(By.NAME,"maTinh").get_attribute("value")
    maHuyen = table.find_element(By.NAME,"maHuyen").get_attribute("value")
    maXa = table.find_element(By.NAME,"maXa").get_attribute("value")
    maDMVung = table.find_element(By.NAME,"maDMVung").get_attribute("value")
    maDMKhuVuc = table.find_element(By.NAME,"maDMKhuVuc").get_attribute("value")
    maNhanVien = table.find_element(By.NAME,"maNhanVien").get_attribute("value")
    maTuyenDoc = table.find_element(By.NAME,"maTuyenDoc").get_attribute("value")
    maPhamVi = table.find_element(By.NAME,"maPhamVi").get_attribute("value")
    maDongHo = table.find_element(By.NAME,"maDongHo").get_attribute("value")
    maDongHoCha = table.find_element(By.NAME,"maDongHoCha").get_attribute("value")
    laDongHoPhu = isCheck(table,"DHP")
    soThuTu = table.find_element(By.NAME,"soThuTu").get_attribute("value")
    seri = table.find_element(By.NAME,"seri").get_attribute("value")
    chiSoDau = table.find_element(By.NAME,"chiSoDau").get_attribute("value")
    chiSoCuoi = table.find_element(By.NAME,"chiSoCuoi").get_attribute("value")
    seriChi = table.find_element(By.NAME,"seriChi").get_attribute("value")
    ngayLapDatDongHo = table.find_element(By.NAME,"ngayLapDatDongHo").get_attribute("value")
    ngayBatDauSuDung = table.find_element(By.NAME,"ngayBatDauSuDung").get_attribute("value")
    diaChi2 = table.find_elements(By.NAME,"diaChi")[1].get_attribute("value")
    maTinhTrangDongHo = table.find_element(By.NAME,"maTinhTrangDongHo").get_attribute("value")
    lyDoHuy = table.find_element(By.NAME,"lyDoHuy").get_attribute("value")
    ngayBatDauNgung = table.find_element(By.NAME,"ngayBatDauNgung").get_attribute("value")
    ngayKetThucSuDung = table.find_element(By.NAME,"ngayKetThucSuDung").get_attribute("value")
    maDMNuocSanXuat = table.find_element(By.NAME,"maDMNuocSanXuat").get_attribute("value")
    maDMHangSanXuat = table.find_element(By.NAME,"maDMHangSanXuat").get_attribute("value")
    maDMKieuDongHo = table.find_element(By.NAME,"maDMKieuDongHo").get_attribute("value")
    duongKinh = table.find_element(By.NAME,"duongKinh").get_attribute("value")
    maDMHopBaoVeDongHo = table.find_element(By.NAME,"maDMHopBaoVeDongHo").get_attribute("value")
    viTriLapDat = table.find_element(By.NAME,"viTriLapDat").get_attribute("value")
    ngayKiemDinh = table.find_element(By.NAME,"ngayKiemDinh").get_attribute("value")
    ngayHieuLucKiemDinh = table.find_element(By.NAME,"ngayHieuLucKiemDinh").get_attribute("value")
    lyDoKiemDinh = table.find_element(By.NAME,"lyDoKiemDinh").get_attribute("value")
    vanMotChieu = table.find_element(By.NAME,"vanMotChieu").get_attribute("value")
    tem = table.find_element(By.NAME,"tem").get_attribute("value")
    soPhieuThay = table.find_element(By.NAME,"soPhieuThay").get_attribute("value")
    hinhThucXuLy = table.find_element(By.NAME,"hinhThucXuLy").get_attribute("value")
    lyDoThay = table.find_element(By.NAME,"lyDoThay").get_attribute("value")
    maDongHoThay = table.find_element(By.NAME,"maDongHoThay").get_attribute("value")
    nguoiThay = table.find_element(By.NAME,"nguoiThay").get_attribute("value")
    xDaiDien = table.find_element(By.NAME,"xDaiDien").get_attribute("value")
    yDaiDien = table.find_element(By.NAME,"yDaiDien").get_attribute("value")
    loaiKhuyenMai = table.find_element(By.NAME,"loaiKhuyenMai").get_attribute("value")
    soNuocKhuyenMaiConLai = table.find_element(By.NAME,"soNuocKhuyenMaiConLai").get_attribute("value")
    trangThaiDongHo = table.find_element(By.NAME,"trangThaiDongHo").get_attribute("value")
    ongDan = table.find_element(By.NAME,"ongDan").get_attribute("value")
    daiKhoiThuy = table.find_element(By.NAME,"daiKhoiThuy").get_attribute("value")
    worksheet.write(count, 0, maKhachHang)
    worksheet.write(count, 1, tenKhachHang)
    worksheet.write(count, 2, diaChi1)
    worksheet.write(count, 3, tenThuongGoi)
    worksheet.write(count, 4, soHoDungChung)
    worksheet.write(count, 5, soNhanKhau)
    worksheet.write(count, 6, email)
    worksheet.write(count, 7, ngayCapCMND)
    worksheet.write(count, 8, noiCapCMND)
    worksheet.write(count, 9, maSoThue)
    worksheet.write(count, 10, nguoiDaiDien)
    worksheet.write(count, 11, doiTuong)
    worksheet.write(count, 12, ghiChu)
    worksheet.write(count, 13, soHopDong)
    worksheet.write(count, 14, maDoiTuongGia)
    worksheet.write(count, 15, mucDich)
    worksheet.write(count, 16, maPhuongThucThanhToan)
    worksheet.write(count, 17, maVach)
    worksheet.write(count, 18, ngayKy)
    worksheet.write(count, 19, ngayLapDat)
    worksheet.write(count, 20, nguoiLapDat)
    worksheet.write(count, 21, ngayBanGiao)
    worksheet.write(count, 22, soTien)
    worksheet.write(count, 23, nguoiNop)
    worksheet.write(count, 24, tienDatCoc)
    worksheet.write(count, 25, loaiGiamTru)
    worksheet.write(count, 26, soTienGiamTru)
    worksheet.write(count, 27, ngayDatCoc)
    worksheet.write(count, 28, chungTuDatCoc)
    worksheet.write(count, 29, camKetSuDungNuoc)
    worksheet.write(count, 30, khoiLuongCamKet)
    worksheet.write(count, 31, ghiChuHD)
    worksheet.write(count, 32, maTinh)
    worksheet.write(count, 33, maHuyen)
    worksheet.write(count, 34, maXa)
    worksheet.write(count, 35, maDMVung)
    worksheet.write(count, 36, maDMKhuVuc)
    worksheet.write(count, 37, maNhanVien)
    worksheet.write(count, 38, maTuyenDoc)
    worksheet.write(count, 39, maPhamVi)
    worksheet.write(count, 40, maDongHo)
    worksheet.write(count, 41, maDongHoCha)
    worksheet.write(count, 42, laDongHoPhu)
    worksheet.write(count, 43, soThuTu)
    worksheet.write(count, 44,seri)
    worksheet.write(count, 45, chiSoDau)
    worksheet.write(count, 46, chiSoCuoi)
    worksheet.write(count, 47, seriChi)
    worksheet.write(count, 48, ngayLapDatDongHo)
    worksheet.write(count, 49, ngayBatDauSuDung)
    worksheet.write(count, 50, diaChi2)
    worksheet.write(count, 51, maTinhTrangDongHo)
    worksheet.write(count, 52, lyDoHuy)
    worksheet.write(count, 53, ngayBatDauNgung)
    worksheet.write(count, 54, ngayKetThucSuDung)
    worksheet.write(count, 55, maDMNuocSanXuat)
    worksheet.write(count, 56, maDMHangSanXuat)
    worksheet.write(count, 57, maDMKieuDongHo)
    worksheet.write(count, 58, duongKinh)
    worksheet.write(count, 59, maDMHopBaoVeDongHo)
    worksheet.write(count, 60, viTriLapDat)
    worksheet.write(count, 61, ngayKiemDinh)
    worksheet.write(count, 62, ngayHieuLucKiemDinh)
    worksheet.write(count, 63, lyDoKiemDinh)
    worksheet.write(count, 64, vanMotChieu)
    worksheet.write(count, 65, tem)
    worksheet.write(count, 66, soPhieuThay)
    worksheet.write(count, 67, hinhThucXuLy)
    worksheet.write(count, 68, lyDoThay)
    worksheet.write(count, 69, maDongHoThay)
    worksheet.write(count, 70, nguoiThay)
    worksheet.write(count, 71, xDaiDien)
    worksheet.write(count, 72, yDaiDien)
    worksheet.write(count, 73, loaiKhuyenMai)
    worksheet.write(count, 74, soNuocKhuyenMaiConLai)
    worksheet.write(count, 75, trangThaiDongHo)
    worksheet.write(count, 76, ongDan)
    worksheet.write(count, 77, daiKhoiThuy)
def isCheck(table,ch):
    cam_ket = table.find_elements(By.CSS_SELECTOR,"input.x-form-checkbox")[9]
    dong_ho_phu = table.find_elements(By.CSS_SELECTOR,"input.x-form-checkbox")[10]
    tick = table.find_elements(By.CSS_SELECTOR,"table.x-form-cb-checked")
    for t in tick:
        for k in t.find_elements(By.CSS_SELECTOR,"input.x-form-checkbox"):
            if(k==dong_ho_phu and ch=="DHP"):
                return "có"
            if(k==cam_ket and ch=="CK"):
                return "có"
    return "không"
count = 1
driver.find_element(By.NAME,'inputItem').clear()
driver.find_element(By.NAME,'inputItem').send_keys(STARPAGE)
driver.find_element(By.NAME,'inputItem').send_keys(Keys.ENTER)
page =int(driver.find_element(By.NAME,'inputItem').get_attribute('value'))
time.sleep(1)
while(page!=ENDPAGE+1):
    table = driver.find_elements(By.CSS_SELECTOR,'table.x-grid-table')[3]
    row = table.find_elements(By.CSS_SELECTOR,'tr.x-grid-row')
    stt = 1
    for i in range(len(row)):
        row[i].click()
        time.sleep(1)
        driver.find_elements(By.CSS_SELECTOR,'span.x-btn-inner')[13].click()
        time.sleep(1)
        table = driver.find_element(By.CSS_SELECTOR,"div.x-window-default")
        data = table.find_elements(By.CSS_SELECTOR,'table.x-grid-table > tbody > tr.x-grid-row')
        maKhachHang = table.find_element(By.NAME,"maKhachHang").get_attribute("value")
        tenKhachHang = table.find_element(By.NAME,"tenKhachHang").get_attribute("value")
        diaChi1 = table.find_elements(By.NAME,"diaChi")[0].get_attribute("value")
        tenThuongGoi = table.find_element(By.NAME,"tenThuongGoi").get_attribute("value")
        soHoDungChung = table.find_element(By.NAME,"soHoDungChung").get_attribute("value")
        soNhanKhau = table.find_element(By.NAME,"soNhanKhau").get_attribute("value")
        email = table.find_element(By.NAME,"email").get_attribute("value")
        ngayCapCMND = table.find_element(By.NAME,"ngayCapCMND").get_attribute("value")
        noiCapCMND = table.find_element(By.NAME,"noiCapCMND").get_attribute("value")
        maSoThue = table.find_element(By.NAME,"maSoThue").get_attribute("value")
        nguoiDaiDien = table.find_element(By.NAME,"nguoiDaiDien").get_attribute("value")
        doiTuong = table.find_element(By.NAME,"doiTuong").get_attribute("value")
        ghiChu = table.find_element(By.NAME,"ghiChu").get_attribute("value")
        soHopDong = table.find_element(By.NAME,"soHopDong").get_attribute("value")
        maDoiTuongGia = table.find_element(By.NAME,"maDoiTuongGia").get_attribute("value")
        mucDich = table.find_element(By.NAME,"mucDich").get_attribute("value")
        maPhuongThucThanhToan = table.find_element(By.NAME,"maPhuongThucThanhToan").get_attribute("value")
        maVach = table.find_element(By.NAME,"maVach").get_attribute("value")
        ngayKy = table.find_element(By.NAME,"ngayKy").get_attribute("value")
        ngayLapDat = table.find_element(By.NAME,"ngayLapDat").get_attribute("value")
        nguoiLapDat = table.find_element(By.NAME,"nguoiLapDat").get_attribute("value")
        ngayBanGiao = table.find_element(By.NAME,"ngayBanGiao").get_attribute("value")
        soTien = table.find_element(By.NAME,"soTien").get_attribute("value")
        nguoiNop = table.find_element(By.NAME,"nguoiNop").get_attribute("value")
        tienDatCoc = table.find_element(By.NAME,"tienDatCoc").get_attribute("value")
        loaiGiamTru = table.find_element(By.NAME,"loaiGiamTru").get_attribute("value")
        soTienGiamTru = table.find_element(By.NAME,"soTienGiamTru").get_attribute("value")
        ngayDatCoc = table.find_element(By.NAME,"ngayDatCoc").get_attribute("value")
        chungTuDatCoc = table.find_element(By.NAME,"chungTuDatCoc").get_attribute("value")
        camKetSuDungNuoc = isCheck(table,"CK")
        khoiLuongCamKet = table.find_element(By.NAME,"khoiLuongCamKet").get_attribute("value")
        xDaiDien = table.find_element(By.NAME,"xDaiDien").get_attribute("value")
        yDaiDien = table.find_element(By.NAME,"yDaiDien").get_attribute("value")
        ghiChuHD  = table.find_element(By.NAME,"ghiChuHD").get_attribute("value")
        for j in range(len(data)):
            try:
                loc = data[j].location
                data[j].click()
                time.sleep(1)
            except Exception as e:
                loc["y"] += 27
                time.sleep(1)
                mouse.move(int(loc["x"]+5), int(loc["y"]+137))
                mouse.click(button='left')
                time.sleep(1)
                print(driver.find_element(By.NAME,"maDongHo").get_attribute("value"))
                f = open("log_hopDong.txt", "a")
                f.write("error at page "+ str(page) + " row " + str(i+1) +" data " +str(j+1)+" "+ str(maKhachHang)+".\n")
                f.close()
            save()
            count +=1
        print(str(stt)+ " -- " +tenKhachHang)
        table.find_element(By.CSS_SELECTOR,"span.iconClose").click()
        stt +=1
    driver.find_element(By.CSS_SELECTOR,'span.x-tbar-page-next').click()
    time.sleep(1)
    print('---------------Trang '+str(page)+' hoàn thành---------------')
    page +=1
workbook.close()
driver.quit()